name: Update RSS Feeds

on:
  schedule:
    - cron: "0 5 * * *" # Tiap hari jam 12 siang WIB (UTC+7)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate all XML feeds
        run: npm start

      - name: Commit and push updated feeds
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add free-*.xml
          git commit -m "Auto-update RSS feeds" || echo "No changes"
          git push
